### ISSUE TITLE
[Feature] Landing Page 구현

### ISSUE THREAD

**Issue by task11** [project-hand/hand-react-typescript-frontend#10]
**Description Feature**
> Landing Page 레이아웃, 모달 출력 기능 구현 (반응형 포함)

**To-Do**
- [x] 랜딩페이지 Layout 구현
- [x] 랜딩페이지 애니메이션 구현
- [x] Modal , Login 컴포넌트 화면 출력 구현
- [x] Modal , Login 컴포넌트 스타일 구현
- [x] 로그인 기능 테스트
