### ISSUE TITLE
[Feature] Layout 구현 및 적용

### ISSUE THREAD

**Issue by task11** [project-hand/hand-react-typescript-frontend#13]
**Description Feature**
> 레이아웃 (Main, Header, Footer, Section) 구현 및 적용

**To-Do**
- [x] Header 레이아웃 구현
- [x] Header Search 레이아웃 + 일부 기능 구현
- [x] Footer 레이아웃 구현
- [x] Main(Section) 레이아웃 구현
- [x] re-rendering 되지 않게 적용
