### ISSUE TITLE
[Feature] Sidebar 구현

### ISSUE THREAD

**Issue by task11** [project-hand/hand-react-typescript-frontend#16]
**Description Feature**
> Slide Sidebar 구현하기(드래그 앤 드랍까지)

**To-Do**
- [x] 사이드 바 레이아웃 구현
- [x] 슬라이드 애니메이션 구현
- [x] 사이드 바 내용 드래그 앤 드랍 구현
